In [303]:
import pandas as pd
df = pd.read_csv("form.csv")
columns = ['time', 'sex', 'child_offence', 'vegan', 'dvach', 'gender', 'rest', 'games', 'series', 'books', 'antisemetism', 'subject', 'crimea', 'putin', 'english', 'old_days', 'films']
oldColumns = df.columns
df = df.rename(columns=dict(zip(oldColumns, columns)) )

df.time = pd.to_datetime(df.time)

df.loc[df.sex == 'Мальчик' ,['sex']] = 0
df.loc[df.sex == 'Девочка' ,['sex']] = 1
df.loc[df.rest == 'Сычевать' ,['rest']] = 1
df.loc[df.rest == 'Гулять' ,['rest']] = 0

df = pd.get_dummies(df, drop_first=True,columns=['child_offence', 'dvach', 'gender', 'antisemetism', 'subject', 'crimea', 'english'])

In [304]:
df['putin_good'] = 0
df.loc[(df.putin == 'Политик, лидер и боец') | (df.putin == 'Молодец'),['putin_good']]=1
df['rebel'] = 1
df.loc[(df.putin == 'Политик, лидер и боец') | (df.putin == 'Молодец'),['putin_good']]=0
df  =df.drop(columns=['putin'])

In [305]:
for i, row in df.iterrows():
    for string in row.films.split(',') :
        a = ' '.join(string.split())
        if a not in df.columns:
            df[a] = 0
        df.at[i, a] = 1
df  =df.drop(columns=['films','old_days'])
df

,time,sex,vegan,rest,games,series,books,child_offence_Разве что по делу,child_offence_Часто,dvach_Не знаю,...,Детектив,Аниме,Драма,Комедия,Исторический фильм,Трагедия,Фантастика,Фильм ужасов,Боевик,Мелодрама
0,2019-09-06 23:22:11,1,2,1,1,1,3,0,0,1,...,1,1,1,1,1,1,1,0,0,0
1,2019-09-06 23:27:43,0,2,1,3,1,2,1,0,0,...,1,0,0,0,0,1,1,1,0,0
2,2019-09-06 23:30:07,1,2,0,0,1,3,1,0,0,...,1,0,0,1,0,0,1,0,1,1
3,2019-09-06 23:30:08,0,0,0,2,3,4,1,0,0,...,1,1,0,1,1,0,1,0,1,1
4,2019-09-06 23:31:38,0,1,1,6,4,3,0,0,0,...,1,1,1,1,1,0,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
193,2020-10-31 18:06:00,0,3,1,6,0,2,1,0,0,...,0,0,1,1,0,1,1,1,0,0
194,2020-10-31 18:56:01,0,2,0,4,4,2,0,1,0,...,1,1,1,1,0,1,1,1,1,0
195,2020-10-31 19:10:22,0,2,0,1,4,4,0,1,0,...,0,1,0,0,0,0,0,0,0,0
196,2020-10-31 20:20:18,0,3,1,4,2,0,0,0,1,...,0,0,0,1,0,0,1,0,1,0
197,2020-10-31 21:42:02,1,2,1,1,4,5,0,1,1,...,1,0,1,1,0,0,1,0,1,0

In [306]:
df.to_csv('ans_form.csv',index=False)